package tftp_perissier_groleau;

import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Epulapp
 */
public class IHM extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public IHM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnEnvoyer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfParcourir = new javax.swing.JTextField();
        btnParcourir = new javax.swing.JButton();
        tfIPEnvoi = new javax.swing.JTextField();
        tfNomFichierDist = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRecevoir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfParcourirDossier = new javax.swing.JTextField();
        btnParcourirDossier = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfIPReception = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNomFichierRecept = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        btnEnvoyer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        jLabel3.setText("Choisir le fichier à envoyer");

        tfParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParcourirActionPerformed(evt);
            }
        });

        btnParcourir.setText("Parcourir");
        btnParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcourirActionPerformed(evt);
            }
        });

        tfIPEnvoi.setToolTipText("");
        tfIPEnvoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIPEnvoiActionPerformed(evt);
            }
        });

        jLabel4.setText("Indiquer l'IP du serveur");

        jLabel5.setText("Saisir le nom du fichier distant");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(425, 425, 425))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tfParcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnParcourir))
                                .addComponent(tfIPEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(tfNomFichierDist, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfParcourir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParcourir))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIPEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomFichierDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnvoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Envoyer un fichier", jPanel1);

        btnRecevoir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRecevoir.setText("Recevoir");
        btnRecevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecevoirActionPerformed(evt);
            }
        });

        jLabel6.setText("Choisir le dossier de réception");
        jLabel6.setToolTipText("");

        tfParcourirDossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParcourirDossierActionPerformed(evt);
            }
        });

        btnParcourirDossier.setText("Parcourir");
        btnParcourirDossier.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnParcourirDossierAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnParcourirDossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcourirDossierActionPerformed(evt);
            }
        });

        jLabel7.setText("Indiquer l'IP du serveur");

        tfIPReception.setToolTipText("");
        tfIPReception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIPReceptionActionPerformed(evt);
            }
        });

        jLabel8.setText("Saisir le nom du fichier à recevoir");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRecevoir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(tfIPReception, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tfParcourirDossier, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnParcourirDossier))
                        .addComponent(tfNomFichierRecept, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfParcourirDossier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParcourirDossier))
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIPReception, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNomFichierRecept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecevoir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Recevoir un fichier", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Envoyer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParcourirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParcourirActionPerformed

    private void btnParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcourirActionPerformed

        JFileChooser ChoixFichierVel = new JFileChooser("./");
        ChoixFichierVel.setDialogTitle("Choisissez le fichier à envoyer");
        ChoixFichierVel.setFileSelectionMode(JFileChooser.FILES_ONLY);// fichiers seulement
        ChoixFichierVel.setAcceptAllFileFilterUsed(false);// ne pas mettre de filtre de fichier
        ChoixFichierVel.setApproveButtonText("Sélectionner fichier"); //intitule du bouton

        if (ChoixFichierVel.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            tfParcourir.setText("");
            String MonFichierVel = (ChoixFichierVel.getSelectedFile().getName() != null) ? ChoixFichierVel.getSelectedFile().getPath() : "";
            tfParcourir.setText(MonFichierVel);

        }
    }//GEN-LAST:event_btnParcourirActionPerformed

    private void tfIPEnvoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIPEnvoiActionPerformed

    }//GEN-LAST:event_tfIPEnvoiActionPerformed

    private void tfParcourirDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParcourirDossierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParcourirDossierActionPerformed

    private void btnParcourirDossierAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnParcourirDossierAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParcourirDossierAncestorAdded

    private void btnParcourirDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcourirDossierActionPerformed
        // TODO add your handling code here:
        JFileChooser ChoixFichierVel = new JFileChooser("./");
        ChoixFichierVel.setDialogTitle("Choisissez le dossier à envoyer");
        ChoixFichierVel.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);// fichiers seulement
        ChoixFichierVel.setAcceptAllFileFilterUsed(false);// ne pas mettre de filtre de fichier
        ChoixFichierVel.setApproveButtonText("Sélectionner dossier"); //intitule du bouton

        if (ChoixFichierVel.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            tfParcourirDossier.setText("");
            File selectedDir = ChoixFichierVel.getSelectedFile();
            if ( !selectedDir.isDirectory() ) {
                selectedDir = selectedDir.getParentFile();
            }
            String MonFichierVel = selectedDir.getPath();
            tfParcourirDossier.setText(MonFichierVel);

        }
    }//GEN-LAST:event_btnParcourirDossierActionPerformed

    private void tfIPReceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIPReceptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIPReceptionActionPerformed

    private void btnRecevoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecevoirActionPerformed
        if(!"".equals(this.tfParcourirDossier.getText()) && !"".equals(this.tfIPReception.getText()) &&  !"".equals(this.tfNomFichierRecept.getText())){
            try {
                // appeler mtd reception
                Client client = new Client();
                InetAddress serveurIP = InetAddress.getByName(this.tfIPReception.getText());
                
                Short Cr_rv = client.run(this.tfParcourirDossier.getText(), this.tfNomFichierRecept.getText(), serveurIP);
                switch (Cr_rv){
                    case 0:
                        JOptionPane.showMessageDialog(this, "Le transfert a bien été réalisé !", "Erreur", JOptionPane.ERROR_MESSAGE);
                        System.out.println("Le transfert a bien été réalisé !");
                        break;
                    case -1:
                        JOptionPane.showMessageDialog(this, "Une erreur locale est survenue !", "Erreur", JOptionPane.ERROR_MESSAGE);
                        System.out.println("Une erreur locale est survenue !");
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(this, "Une erreur de transfert est intervenue sur le serveur !", "Erreur", JOptionPane.ERROR_MESSAGE);
                        System.out.println("Une erreur de transfert est intervenue sur le serveur !");
                        break;
                }
                
            } catch (SocketException ex) {
                Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnknownHostException ex) {
                Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(IHM.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Pour recevoir le fichier, vous devez renseigner tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRecevoirActionPerformed

    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
        if(!"".equals(this.tfParcourir.getText()) && !"".equals(this.tfIPEnvoi.getText()) &&  !"".equals(this.tfNomFichierDist.getText())){
            // appeler mtd envoyer
        }else{
            JOptionPane.showMessageDialog(this, "Pour envoyer le fichier, vous devez renseigner tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JButton btnParcourir;
    private javax.swing.JButton btnParcourirDossier;
    private javax.swing.JButton btnRecevoir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfIPEnvoi;
    private javax.swing.JTextField tfIPReception;
    private javax.swing.JTextField tfNomFichierDist;
    private javax.swing.JTextField tfNomFichierRecept;
    private javax.swing.JTextField tfParcourir;
    private javax.swing.JTextField tfParcourirDossier;
    // End of variables declaration//GEN-END:variables
}
